style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/loft-sh/virtual-cluster
options:
  commits:
#    filters:
#      Type:
#        - feat
#        - fix
#        - perf
#        - refactor
#        - docs
  commit_groups:
    title_maps:
      feat: ğŸš€ New Features
      fix: ğŸ› Bug Fixes
      perf: ğŸƒâ€â™€ï¸ Performance Improvements
      chart: ğŸ“Š Helm Chart
      refactor: ğŸ’¡ Code Refactoring
      style: ğŸ’… Code Style & Formatting
      test: ğŸ§ª Tests Added/Fixed
      build: ğŸ§± Build Process Changes
      ci: ğŸ¤– Changes to CI/CD
  header:
    pattern: "(?i)^(?:((?:feat)|(?:fix)|(?:perf)|(?:refactor)|(?:style)|(?:test)|(?:docs)|(?:build)|(?:ci)|)(?:(?:(?:[^):]*)\\()?([^)]*)\\)?)?:)?(.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "(?i)^Merges?(?: branch ')?(.+?)'?$"
    pattern_maps:
      - Source
  reverts:
    pattern: "(?i)^Reverts?(?: \")?(.+?)(?:\")?$"
    pattern_maps:
      - Header
  notes:
    keywords:
      - BREAKING CHANGE
      - "!"
